USE VersicherungsDB
GO

DROP PROCEDURE IF EXISTS list_products_by_category
GO

CREATE PROCEDURE list_products_by_category @category_id INT
AS
	BEGIN TRANSACTION
	SET TRANSACTION ISOLATION LEVEL READ COMMITTED

	BEGIN TRY

		IF (SELECT COUNT(*) FROM PRODUKT_KATEGORIE WHERE PRODUKT_KATEGORIE.ID = @category_id) != 1
			THROW 60000, 'invalid category id', 1

		SELECT NAME, BESCHREIBUNG
		FROM PRODUKTE
		WHERE FK_ID_PRODUKT_KATEGORIE = @category_id

		COMMIT TRANSACTION

	END TRY
	BEGIN CATCH

		PRINT ERROR_MESSAGE()
		ROLLBACK TRANSACTION

	END CATCH
GO