---Forward Only Cursor
USE VersicherungsDB
GO

DECLARE @BESTELLUNGENID INT
DECLARE @getBESTELLUNGENID CURSOR

SET @getBESTELLUNGENID  = CURSOR FORWARD_ONLY FOR 


SELECT BESTELLUNGEN.ID
FROM BESTELLUNGEN
INNER JOIN USERS 
ON USERS.ID = BESTELLUNGEN.FK_ID_USERS
WHERE TIMESTAMP > '01.12.2018';

OPEN @getBESTELLUNGENID 
FETCH NEXT
FROM @getBESTELLUNGENID INTO @BESTELLUNGENID
WHILE @@FETCH_STATUS = 0

BEGIN
PRINT @BESTELLUNGENID
FETCH NEXT
FROM @getBESTELLUNGENID INTO @BESTELLUNGENID
END

CLOSE @getBESTELLUNGENID 
DEALLOCATE @getBESTELLUNGENID

-------------------------------------------------
USE VersicherungsDB
GO

DECLARE @PRODUKTEID INT
DECLARE @getPRODUKTEID CURSOR

SET @getPRODUKTEID = CURSOR FOR SELECT ID FROM PRODUKTE


SELECT PRODUKTE.ID
FROM PRODUKTE
INNER JOIN PRODUKTE_ANBIETER 
ON PRODUKTE.ID = PRODUKTE_ANBIETER.FK_ID_PRODUKTE
WHERE PRODUKTE_ANBIETER.PREIS <= 100;

OPEN @getPRODUKTEID
FETCH NEXT
FROM @getPRODUKTEID INTO @PRODUKTEID
WHILE @@FETCH_STATUS = 0

BEGIN
PRINT @PRODUKTEID
FETCH NEXT
FROM @getPRODUKTEID INTO @PRODUKTEID
END

CLOSE @getPRODUKTEID
DEALLOCATE @getPRODUKTEID