USE VersicherungsDB
GO

DECLARE @Fr VARCHAR(300)
DECLARE @Antw VARCHAR(300)
DECLARE @getANSWEREDQUESTIONS CURSOR

SET @getANSWEREDQUESTIONS = CURSOR FORWARD_ONLY FOR SELECT FRAGE, ANTWORT FROM FRAGEN


SELECT FRAGEN.FRAGE, FRAGEN.ANTWORT
FROM FRAGEN
WHERE FRAGEN.ANTWORT IS NOT NULL;

OPEN @getANSWEREDQUESTIONS
FETCH NEXT
FROM @getANSWEREDQUESTIONS INTO @Fr, @Antw
WHILE @@FETCH_STATUS = 0

BEGIN
PRINT @Fr
PRINT @Antw
FETCH NEXT
FROM @getANSWEREDQUESTIONS INTO @Fr, @Antw
END

CLOSE @getANSWEREDQUESTIONS
DEALLOCATE @getANSWEREDQUESTIONS