USE master

SET LANGUAGE us_english;
PRINT('SYS-LANGUAGE NOW: '+@@language)
GO
SET DATEFORMAT dmy;
DECLARE @Current_DateFormat VARCHAR(30)
SELECT @Current_DateFormat = (select s.date_format from sys.dm_exec_sessions s where s.session_id = @@SPID );
PRINT('SYS-DATEFORMAT NOW: '+@Current_DateFormat)
GO

-- Create login
if not EXISTS
    (select * from sys.sql_logins where name = 'DB_User')
begin
    create login DB_User with PASSWORD = 'MasterPW'
END

-- Create user
drop user if exists DB_User
CREATE USER DB_User FOR LOGIN DB_User

-- default access for every user
grant 
connect, insert, update, delete, select, alter, execute
to DB_User

IF EXISTS(select * from sys.databases where name='VersicherungsDB')
	DROP DATABASE VersicherungsDB
	PRINT('OLD "VersicherungsDB" DATABASE DELETED')

CREATE DATABASE VersicherungsDB
GO
USE VersicherungsDB
GO
PRINT('DATABASE "VersicherungsDB" CREATED')

DROP TABLE IF EXISTS dbo.USERS
DROP TABLE IF EXISTS dbo.ANBIETER
DROP TABLE IF EXISTS dbo.PRODUKT_KATEGORIE
DROP TABLE IF EXISTS dbo.BERATER
DROP TABLE IF EXISTS dbo.BEWERTUNG_ANBIETER
DROP TABLE IF EXISTS dbo.BEWERTUNG_ANBIETER_PROD
DROP TABLE IF EXISTS dbo.BEWERTUNG_BERATER
DROP TABLE IF EXISTS dbo.PRODUKTE_ANBIETER
DROP TABLE IF EXISTS dbo.BESTELLUNGEN
DROP TABLE IF EXISTS dbo.PRODUKTE
DROP TABLE IF EXISTS dbo.FRAGEN
GO
PRINT('IF EXISTED: OLD TABLES DELETED')

CREATE TABLE [USERS]
(
   [ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   [PASSWORDHASH] BINARY(64) NOT NULL, --PASSWORDHASH = SHA2_512
   [NAME] VARCHAR(30) NOT NULL UNIQUE,
   [GEBURTSTAG] DATE  NOT NULL,
   [WOHNORT] varchar(50) NOT NULL,
   [IS_ADMIN] BIT NOT NULL DEFAULT 0,
   [IS_BERATER] BIT NOT NULL DEFAULT 0
)
GO
CREATE TABLE [ANBIETER]
(
	[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[NAME] VARCHAR(30) NOT NULL UNIQUE,
	[ADRESSE] VARCHAR(50) NOT NULL
)
GO
CREATE TABLE [PRODUKT_KATEGORIE]
(
	[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[NAME] VARCHAR (50) NOT NULL
)
GO
CREATE TABLE [PRODUKTE]
(
	[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[FK_ID_PRODUKT_KATEGORIE] INT NOT NULL,
	[NAME] VARCHAR(50) NOT NULL,
	[BESCHREIBUNG] VARCHAR(200) NOT NULL,
	CONSTRAINT FK_PRODUKTE_ID_PRODUKT_KATEGORIE FOREIGN KEY (FK_ID_PRODUKT_KATEGORIE)
		REFERENCES dbo.PRODUKT_KATEGORIE (ID)
)
GO
CREATE TABLE [BERATER]
(
	[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[FK_ID_ANB] INT NOT NULL,
	[FK_ID_USERS] INT NOT NULL
	CONSTRAINT FK_BERATER_ID_ANBIETER FOREIGN KEY (FK_ID_ANB)     
		REFERENCES dbo.ANBIETER (ID)
			ON UPDATE CASCADE,
	CONSTRAINT FK_BERATER_ID_USERS FOREIGN KEY (FK_ID_USERS)
		REFERENCES dbo.USERS (ID)
			ON DELETE CASCADE
			ON UPDATE CASCADE
)
GO
CREATE TABLE [BEWERTUNG_ANBIETER]
(
	[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[FK_ID_USERS] INT NOT NULL,
	[FK_ID_ANBIETER] INT NOT NULL,
	[STERNE] numeric(1,0) NOT NULL,
	CONSTRAINT FK_BEWERTUNG_ANBIETER_ID_USERS FOREIGN KEY (FK_ID_USERS)     
		REFERENCES dbo.USERS (ID)
			ON UPDATE CASCADE,
	CONSTRAINT FK_BEWERTUNG_ANBIETER_ID_ANBIETER FOREIGN KEY (FK_ID_ANBIETER)     
		REFERENCES dbo.ANBIETER (ID)
			ON DELETE CASCADE 
			ON UPDATE CASCADE
)
GO
CREATE TABLE [PRODUKTE_ANBIETER]
(
	[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[FK_ID_ANBIETER] INT NOT NULL,
	[FK_ID_PRODUKTE] INT NOT NULL,
	[PREIS] DECIMAL(10,2) NOT NULL,
	[LAUFZEIT] NUMERIC(3,0) NOT NULL
	CONSTRAINT FK_PRODUKTE_ANBIETER_ID_ANBIETER FOREIGN KEY (FK_ID_ANBIETER)     
		REFERENCES dbo.ANBIETER (ID)     
			ON DELETE CASCADE 
			ON UPDATE CASCADE,
	CONSTRAINT FK_PRODUKTE_ANBIETER_ID_PRODUKTE FOREIGN KEY (FK_ID_PRODUKTE)     
		REFERENCES dbo.PRODUKTE (ID)
			ON UPDATE CASCADE
)
GO
CREATE TABLE [BEWERTUNG_ANBIETER_PROD]
(
	[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[FK_ID_USERS] INT NOT NULL,
	[FK_ID_PRODUKTE_ANBIETER] INT NOT NULL,
	[STERNE] numeric(1,0) NOT NULL,
	CONSTRAINT FK_BEWERTUNG_ANBIETER_PROD_ID_USERS FOREIGN KEY (FK_ID_USERS)     
		REFERENCES dbo.USERS (ID)
			ON UPDATE CASCADE,
	CONSTRAINT FK_BEWERTUNG_ANBIETER_PROD_ID_PRODUKTE_ANBIETER FOREIGN KEY (FK_ID_PRODUKTE_ANBIETER)     
		REFERENCES dbo.PRODUKTE_ANBIETER (ID)
			ON DELETE CASCADE 
			ON UPDATE CASCADE    
)
GO
CREATE TABLE [BEWERTUNG_BERATER]
(
	[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[FK_ID_USERS] INT NOT NULL,
	[FK_ID_BERATER] INT NOT NULL,
	[STERNE] NUMERIC(1,0) NOT NULL
	CONSTRAINT FK_BEWERTUNG_BERATER_ID_USERS FOREIGN KEY (FK_ID_USERS)     
		REFERENCES dbo.USERS (ID)
			ON UPDATE CASCADE,
	CONSTRAINT FK_BEWERTUNG_BERATER_ID_BERATER FOREIGN KEY (FK_ID_BERATER)     
		REFERENCES dbo.BERATER (ID)  
)
GO
CREATE TABLE [BESTELLUNGEN]
(
	[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[FK_ID_USERS] INT NOT NULL,
	[FK_ID_PRODUKTE_ANBIETER] INT nOT NULL,
	[TIMESTAMP] DATETIME2(3) NOT NULL DEFAULT SYSDATETIME(),
	CONSTRAINT FK_BESTELLUNGEN_ID_USERS FOREIGN KEY (FK_ID_USERS)     
		REFERENCES dbo.USERS (ID)
			ON UPDATE CASCADE,
	CONSTRAINT FK_BESTELLUNGEN_ID_PRODUKTE_ANBIETER FOREIGN KEY (FK_ID_PRODUKTE_ANBIETER)     
		REFERENCES dbo.PRODUKTE_ANBIETER (ID)
			ON UPDATE CASCADE
)
GO
CREATE TABLE [FRAGEN]
(
	[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[FK_ID_USERS] INT NOT NULL,
	[FK_ID_BERATER_FRAGEN] INT NULL,
	[FRAGE] VARCHAR(300) NOT NULL,
	[ANTWORT] VARCHAR(300) NULL,
	[STMP_FRAGE] DATETIME2(3) NOT NULL DEFAULT SYSDATETIME(),
	[STMP_ANTWORT] DATETIME2(3) NULL,
	CONSTRAINT FK_FRAGEN_ID_USERS FOREIGN KEY (FK_ID_USERS)     
		REFERENCES dbo.USERS (ID)
			ON DELETE CASCADE 
			ON UPDATE CASCADE
)
GO
CREATE TABLE [BERATER_FRAGEN] --ZWISCHENTABELLE DA BERATER ZU FRAGEN N ZU M BEZIEHUNG!
(
	[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[FK_ID_BERATER] INT NULL,
	[FK_ID_FRAGE] INT NULL,
	CONSTRAINT FK_FRAGEN_ID_BERATER FOREIGN KEY (FK_ID_BERATER)     
		REFERENCES dbo.BERATER (ID)
			ON UPDATE CASCADE,
	CONSTRAINT FK_BERATER_FRAGEN_ID_FRAGEN FOREIGN KEY (FK_ID_FRAGE)
		REFERENCES dbo.FRAGEN (ID)
)
GO

PRINT('TABLES CREATED')