USE VersicherungsDB
Go

--FOR TESTING PURPOSE: HARDCODED VIEWs zur Anzeige der Bestellungen nach Anbietern

DROP VIEW IF EXISTS view_show_best_generali
GO
DROP VIEW IF EXISTS view_show_best_uniqa
GO
DROP VIEW IF EXISTS view_show_best_wr_staedtische
GO
DROP VIEW IF EXISTS view_show_best_allianz
GO


CREATE VIEW view_show_best_generali
AS
	SELECT BESTELLUNGEN.ID,BESTELLUNGEN.FK_ID_USERS,BESTELLUNGEN.FK_ID_PRODUKTE_ANBIETER,BESTELLUNGEN.TIMESTAMP FROM BESTELLUNGEN	-- Holen der Bestellungsdaten von Generali Produkten
	INNER JOIN	
		(Select PRODUKTE_ANBIETER.ID as prod_anb_id FROM ANBIETER	--Holen der IDs der Generali Produkte
		LEFT JOIN PRODUKTE_ANBIETER
		ON ANBIETER.ID = PRODUKTE_ANBIETER.FK_ID_ANBIETER
		WHERE ANBIETER.NAME LIKE 'Generali AG') tmp
	ON BESTELLUNGEN.FK_ID_PRODUKTE_ANBIETER = tmp.prod_anb_id
GO

CREATE VIEW view_show_best_uniqa
AS
	SELECT BESTELLUNGEN.ID,BESTELLUNGEN.FK_ID_USERS,BESTELLUNGEN.FK_ID_PRODUKTE_ANBIETER,BESTELLUNGEN.TIMESTAMP FROM BESTELLUNGEN
	INNER JOIN 
		(Select PRODUKTE_ANBIETER.ID as prod_anb_id FROM ANBIETER
		LEFT JOIN PRODUKTE_ANBIETER
		ON ANBIETER.ID = PRODUKTE_ANBIETER.FK_ID_ANBIETER
		WHERE ANBIETER.NAME LIKE 'UNIQA AG') tmp
	ON BESTELLUNGEN.FK_ID_PRODUKTE_ANBIETER = tmp.prod_anb_id
GO

CREATE VIEW view_show_best_wr_staedtische
AS
	SELECT BESTELLUNGEN.ID,BESTELLUNGEN.FK_ID_USERS,BESTELLUNGEN.FK_ID_PRODUKTE_ANBIETER,BESTELLUNGEN.TIMESTAMP FROM BESTELLUNGEN
	INNER JOIN 
		(Select PRODUKTE_ANBIETER.ID as prod_anb_id FROM ANBIETER
		LEFT JOIN PRODUKTE_ANBIETER
		ON ANBIETER.ID = PRODUKTE_ANBIETER.FK_ID_ANBIETER
		WHERE ANBIETER.NAME LIKE 'WIENER STÄDTISCHE AG') tmp
	ON BESTELLUNGEN.FK_ID_PRODUKTE_ANBIETER = tmp.prod_anb_id
GO

CREATE VIEW view_show_best_allianz
AS
	SELECT BESTELLUNGEN.ID,BESTELLUNGEN.FK_ID_USERS,BESTELLUNGEN.FK_ID_PRODUKTE_ANBIETER,BESTELLUNGEN.TIMESTAMP FROM BESTELLUNGEN
	INNER JOIN 
		(Select PRODUKTE_ANBIETER.ID as prod_anb_id FROM ANBIETER
		LEFT JOIN PRODUKTE_ANBIETER
		ON ANBIETER.ID = PRODUKTE_ANBIETER.FK_ID_ANBIETER
		WHERE ANBIETER.NAME LIKE 'Allianz AG') tmp
	ON BESTELLUNGEN.FK_ID_PRODUKTE_ANBIETER = tmp.prod_anb_id
GO