USE VersicherungsDB
GO

DROP PROCEDURE IF EXISTS list_all_categories
GO

CREATE PROCEDURE list_all_categories
AS
	BEGIN TRANSACTION
	SET TRANSACTION ISOLATION LEVEL READ COMMITTED

	SELECT * FROM PRODUKT_KATEGORIE

	COMMIT TRANSACTION
GO